export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE = "GET_MOVIE";
export const MOVIE_SEARCHED = "MOVIE_SEARCHED";
export const MOVIE_ADDED = "MOVIE_ADDED";
export const CLEAR_MOVIE = "CLEAR_MOVIE";
export const CLEAR_MOVIES = "CLEAR_MOVIES";
export const CLEAR_MOVIE_ADDED = "CLEAR_MOVIE_ADDED";
export const GET_NEXT_MOVIES = "GET_NEXT_MOVIES";
export const SET_MOVIES_NOW = "SET_MOVIES_NOW";
export const SET_MOVIES_POPULAR = "SET_MOVIES_POPULAR";
export const SET_MOVIES_TOP = "SET_MOVIES_TOP";
export const SET_SEARCHED = "SET_SEARCHED";

export const GET_PROFILES = "GET_PROFILES";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const DELETE_BUCKET_ITEM = "DELETE_BUCKET_ITEM";
export const DELETE_WATCHED_ITEM = "DELETE_WATCHED_ITEM";

export const REGISTER_USER = "REGISTER_USER";
export const SET_CURRENT_USER = "GET_USER";
